/**
 * Idea Proposer — Sage + Atlas 가 자체 데이터 기반으로 주제를 제안하는 모드.
 *
 * "입력 모드"는 사용자가 키워드를 주고 아이디어를 받는 방식.
 * "제안 모드"는 이 함수가 에이전트 관점에서 데이터(경쟁·시즌·성과)를 분석해
 * 카테고리 내에서 가장 임팩트 높은 주제 10개를 직접 제안.
 */

import type { TargetKPI } from "./schema"

// ── Big Categories (5개로 제한) ─────────────────────────
export const IDEA_CATEGORIES = [
  {
    id: "region",
    label: "지역 가이드",
    emoji: "🗺",
    description: "동네별 시세·매물·생활",
    primaryKPI: "conversion" as TargetKPI,
    lead: "search",
  },
  {
    id: "university",
    label: "대학 가이드",
    emoji: "🎓",
    description: "학교별 주거·시세·유학생 팁",
    primaryKPI: "conversion" as TargetKPI,
    lead: "stra",
  },
  {
    id: "life",
    label: "생활 정보",
    emoji: "💡",
    description: "ARC·은행·가전 등 한국 생활 실용",
    primaryKPI: "traffic" as TargetKPI,
    lead: "search",
  },
  {
    id: "story",
    label: "거주 후기",
    emoji: "📖",
    description: "유학생·노마드·주재원 실제 경험담",
    primaryKPI: "dwell_time" as TargetKPI,
    lead: "stra",
  },
  {
    id: "purpose",
    label: "목적별 가이드",
    emoji: "🎯",
    description: "한달살기·출장·이사·워케이션",
    primaryKPI: "conversion" as TargetKPI,
    lead: "stra",
  },
] as const

export type CategoryId = typeof IDEA_CATEGORIES[number]["id"]

// ── Data-driven rationale types ──────────────────────────
export interface ProposedIdea {
  title: string
  kpi: TargetKPI
  category: CategoryId
  rationale: string // 왜 이 주제를 제안하는지 데이터 근거
  signal: {
    type: "seo-gap" | "top-performer" | "seasonal" | "competitor-miss" | "search-rising"
    detail: string
  }
  difficulty: "low" | "medium" | "high"
  estimatedImpact: "high" | "medium" | "low"
  leadAgent: string
  supportAgents: string[]
  relatedKeywords: string[]
}

// ── Proposer per category ────────────────────────────────
// 실제 구현 시 Sage (SEO) + Atlas (Strategy) 가 협업해서
// 데이터(GA4·SEMrush·경쟁사 크롤·내부 성과)를 분석. 현재는 Mock.

const PROPOSALS: Record<CategoryId, ProposedIdea[]> = {
  region: [
    {
      title: "성수동 단기임대 완벽 가이드 — 노마드 핫플 2026",
      kpi: "conversion",
      category: "region",
      rationale:
        "성수 검색량 전월 대비 +27%, 경쟁사 엔코스테이는 표면만 커버. 매물 임베드와 시세 테이블로 전환 극대화 가능.",
      signal: { type: "search-rising", detail: "성수 단기임대 검색 +27% MoM" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["stra", "haru"],
      relatedKeywords: ["성수 한달살기", "성수 원룸 시세", "성수 노마드"],
    },
    {
      title: "이태원 단기임대 — 외국인 커뮤니티 근처 매물 TOP 7",
      kpi: "conversion",
      category: "region",
      rationale:
        "이태원 지역 키워드는 엔코스테이·미스터멘션 모두 커버 약함. 외국인 유학생·주재원 직격 세그먼트.",
      signal: { type: "competitor-miss", detail: "경쟁사 이태원 커버리지 3편 이하" },
      difficulty: "medium",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["이태원 외국인", "한남 단기임대", "용산 원룸"],
    },
    {
      title: "강남 출장자 숙소 베스트 — 판교·여의도 포함",
      kpi: "conversion",
      category: "region",
      rationale:
        "강남·판교 출장 수요는 상시 높은데 플라트 매물 커버리지 아직 10개 미만. 법인 결제·세금계산서 각도로 차별화.",
      signal: { type: "seo-gap", detail: "강남 월세 오피스텔 키워드 TOP 10 내 플라트 0건" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "search",
      supportAgents: ["stra", "pulse"],
      relatedKeywords: ["강남 출장 숙소", "판교 단기임대", "여의도 오피스텔"],
    },
    {
      title: "제주 한달살기 — 봄 시즌 워케이션 매물 가이드",
      kpi: "conversion",
      category: "region",
      rationale:
        "4~5월 제주 한달살기 시즌 성수기. 플라트 제주 매물 증가했으나 콘텐츠 매칭 부족.",
      signal: { type: "seasonal", detail: "4~5월 제주 한달살기 검색 +45% 예상" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["search", "vibe"],
      relatedKeywords: ["제주 한달살기", "제주 워케이션", "제주 바다뷰"],
    },
    {
      title: "신촌 유학생 방 가이드 — 연대·이대 근처 시세 비교",
      kpi: "traffic",
      category: "region",
      rationale: "신촌 키워드 검색량 안정적, 롱테일 확장 여지 크다. 대학 가이드와 교차 링크 가능.",
      signal: { type: "top-performer", detail: "유사 '서울대 근처' 글 조회 +34%" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["신촌 방", "연대 근처", "이대 유학생"],
    },
    {
      title: "홍대 단기임대 완벽 가이드 — 노마드·어학생",
      kpi: "conversion",
      category: "region",
      rationale: "홍대는 꾸준한 수요. 경쟁사 대비 어학생(연수비자) 각도가 비어있음.",
      signal: { type: "competitor-miss", detail: "어학생 전용 매물 가이드 경쟁 0" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["홍대 한달살기", "홍대 어학당 방", "홍대 D-4"],
    },
    {
      title: "건대·성균관대 인근 단기임대 — 유학생 최다 지역",
      kpi: "traffic",
      category: "region",
      rationale: "건대·성균관대는 유학생 비중이 높음에도 플라트 커버리지 하위. SEO 기회 큼.",
      signal: { type: "seo-gap", detail: "건대 유학생 방 상위 20개 중 플라트 랭크 1개" },
      difficulty: "medium",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["건대 유학생", "성균관대 방", "화양동 원룸"],
    },
    {
      title: "부산 해운대·서면 단기임대 — 지방 한달살기 TOP",
      kpi: "conversion",
      category: "region",
      rationale: "부산 한달살기 수요는 급증 중. 서울 다음 2순위 카테고리로 포지셔닝 가능.",
      signal: { type: "search-rising", detail: "부산 한달살기 +52% YoY" },
      difficulty: "medium",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["부산 한달살기", "해운대 단기임대", "서면 원룸"],
    },
    {
      title: "서초·반포 레지던스형 단기임대 — 주재원 수요",
      kpi: "conversion",
      category: "region",
      rationale: "주재원·법인 수요는 객단가 높음. 플라트 프리미엄 매물 존재하지만 콘텐츠 부재.",
      signal: { type: "seo-gap", detail: "서초 레지던스 키워드 커버리지 0" },
      difficulty: "high",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["pulse"],
      relatedKeywords: ["서초 레지던스", "반포 단기임대", "주재원 숙소"],
    },
    {
      title: "마포·공덕 단기임대 — 직장인·커플 타겟",
      kpi: "traffic",
      category: "region",
      rationale: "마포·공덕은 교통 허브, 검색량 안정. 커플·둘이 살기 각도 아직 비어있음.",
      signal: { type: "competitor-miss", detail: "커플 단기임대 카테고리 경쟁 약함" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["마포 한달살기", "공덕 투룸", "여의도 접근"],
    },
  ],
  university: [
    {
      title: "서울대 유학생 주거 가이드 — 기숙사 vs 자취 비교",
      kpi: "conversion",
      category: "university",
      rationale: "서울대 키워드는 경쟁 중간, 유학생 직격. '기숙사 탈락' 각도는 독점 가능.",
      signal: { type: "search-rising", detail: "서울대 기숙사 탈락 관련 검색 증가" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["서울대 기숙사", "관악구 유학생", "봉천동 원룸"],
    },
    {
      title: "연세대·이대 단기임대 — 신촌 시세·교통 완벽 분석",
      kpi: "conversion",
      category: "university",
      rationale: "연대·이대는 신촌 공유. 두 대학 묶어서 교차 커버하면 효율 상승.",
      signal: { type: "top-performer", detail: "유사 연대 글 전환율 상위 15%" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["연세대 근처", "이대 유학생", "신촌 방"],
    },
    {
      title: "고려대 주거 가이드 — 안암·제기동 시세 매핑",
      kpi: "traffic",
      category: "university",
      rationale: "고려대 키워드 검색 안정, SEO 갭 확인. 유학생 많은 단과대 기준으로 각도 차별화.",
      signal: { type: "seo-gap", detail: "고려대 유학생 TOP 10 중 플라트 랭크 2개" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["고려대 안암", "고대 유학생", "제기동 원룸"],
    },
    {
      title: "건국대 외국인 유학생 방 추천 — 화양동 핫스팟",
      kpi: "conversion",
      category: "university",
      rationale: "건대는 외국인 유학생 비중 서울 최상위. 플라트 매물 많은데 콘텐츠 매칭 부족.",
      signal: { type: "seo-gap", detail: "건대 유학생 전환 키워드 랭킹 5위 이하" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["건국대 유학생", "화양동 방", "건대입구역"],
    },
    {
      title: "한양대 · 성균관대 · 중앙대 단기임대 — 이공계 유학생 편",
      kpi: "traffic",
      category: "university",
      rationale: "이공계 대학원·연구실 유학생은 장기 체류 성향. 프리미엄 매물로 연결 가능.",
      signal: { type: "competitor-miss", detail: "이공계·대학원 각도 경쟁 0" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["한양대 유학생", "성균관대 방", "중앙대 흑석"],
    },
    {
      title: "카이스트·포항공대 방문학자 단기임대",
      kpi: "dwell_time",
      category: "university",
      rationale: "지방 이공계 방문학자 수요는 특수하지만 단가 높고 장기. 롱테일 SEO 기회.",
      signal: { type: "seo-gap", detail: "방문학자 숙소 키워드 블루오션" },
      difficulty: "high",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["카이스트 방문학자", "포항공대 숙소"],
    },
    {
      title: "외대·국제학부 단기임대 — 다국적 학생 타겟",
      kpi: "traffic",
      category: "university",
      rationale: "외대·국제학부는 다국적 학생 집중. 다국어 콘텐츠와 결합 효과 큼.",
      signal: { type: "seo-gap", detail: "외대 유학생 다국어 콘텐츠 부족" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "search",
      supportAgents: ["vibe"],
      relatedKeywords: ["외대 유학생", "국제학부 방", "다국어 단기임대"],
    },
    {
      title: "교환학생 전용 — 한 학기 단기임대 체크리스트",
      kpi: "traffic",
      category: "university",
      rationale: "교환학생 학기 단위 수요 시즌성 강함 (2·8월). 프리시즌 트래픽 확보.",
      signal: { type: "seasonal", detail: "교환학생 신청 시즌 직전 트래픽 피크" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["교환학생 한국", "한 학기 방", "exchange student Korea"],
    },
    {
      title: "어학당 수강생 단기임대 가이드 (D-4 비자)",
      kpi: "conversion",
      category: "university",
      rationale: "어학당(D-4) 학생은 3~6개월 체류로 플라트 기간과 완벽 매칭.",
      signal: { type: "search-rising", detail: "어학당 방 검색 꾸준 증가" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["어학당 방", "D-4 비자", "연수비자 숙소"],
    },
    {
      title: "대학원생·박사과정 장기 자취 — 연구실 근처 매물",
      kpi: "dwell_time",
      category: "university",
      rationale: "대학원생은 장기 체류 + 높은 LTV. 브랜드 신뢰 중심 콘텐츠 필요.",
      signal: { type: "competitor-miss", detail: "대학원생 각도 경쟁 0" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["echo"],
      relatedKeywords: ["대학원 자취", "연구실 근처", "박사과정 주거"],
    },
  ],
  life: [
    {
      title: "외국인등록증(ARC) 3주 완성 가이드",
      kpi: "traffic",
      category: "life",
      rationale: "ARC 키워드는 경쟁 약하고 롱테일 풍부. 플라트 거주숙소제공확인서 혜택과 직결.",
      signal: { type: "seo-gap", detail: "ARC 관련 상위 10건 중 서비스 연결 콘텐츠 0" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["stra", "haru"],
      relatedKeywords: ["ARC 발급", "외국인등록증", "거주숙소제공확인서"],
    },
    {
      title: "외국인 인터넷은행 3사 비교 — 케이뱅크·토스·우리WON",
      kpi: "traffic",
      category: "life",
      rationale: "ARC 다음으로 가장 많이 검색되는 '한국 생활 첫 단계' 키워드.",
      signal: { type: "top-performer", detail: "블루그라운드·엔코 유사 글 트래픽 상위" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["haru"],
      relatedKeywords: ["외국인 은행 계좌", "케이뱅크 외국인", "토스 외국인"],
    },
    {
      title: "한국식 세탁기·건조기 사용법 (버튼 번역 완전판)",
      kpi: "dwell_time",
      category: "life",
      rationale: "외국인만 헤매는 주제. 엔코 유사 글 트래픽 높음. 이미지·영상 리퍼포징 유리.",
      signal: { type: "top-performer", detail: "엔코 Home 카테고리 TOP 1" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "haru",
      supportAgents: ["vibe"],
      relatedKeywords: ["한국 세탁기", "건조기 사용법", "세제·섬유유연제"],
    },
    {
      title: "티머니·기후동행카드 완전 정복 — 외국인용",
      kpi: "traffic",
      category: "life",
      rationale: "기후동행카드 2024 론칭 후 외국인 사용 가이드 부족. SEO 블루오션.",
      signal: { type: "search-rising", detail: "기후동행카드 검색 +180%" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["haru"],
      relatedKeywords: ["기후동행카드", "티머니 외국인", "서울 지하철"],
    },
    {
      title: "분리수거 완벽 가이드 — 외국인이 꼭 알아야 할 한국식 쓰레기",
      kpi: "dwell_time",
      category: "life",
      rationale: "입주 직후 가장 자주 묻는 주제. 매물 상세 페이지에서 링크 유도 효과.",
      signal: { type: "competitor-miss", detail: "경쟁사 커버 약함" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "haru",
      supportAgents: ["vibe"],
      relatedKeywords: ["분리수거", "쓰레기 종량제", "음식물 쓰레기"],
    },
    {
      title: "서울 다국어 병원 10곳 — 영어·중국어·일본어 진료",
      kpi: "traffic",
      category: "life",
      rationale: "의료·건강은 외국인 체류자 공통 니즈. 파트너 병원 제휴 가능성도.",
      signal: { type: "seo-gap", detail: "다국어 병원 리스트 상위 블루오션" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["서울 영어 병원", "외국인 진료", "다국어 병원"],
    },
    {
      title: "배달앱 한국어 몰라도 쓰는 법 — 배민·쿠팡이츠·요기요",
      kpi: "dwell_time",
      category: "life",
      rationale: "일상적 사용 빈도 최상. 엔지니어링팀과 협업해 실사용 스크린 가이드.",
      signal: { type: "top-performer", detail: "배달앱 관련 상위권 경쟁 없음" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "haru",
      supportAgents: ["vibe"],
      relatedKeywords: ["배민 외국인", "쿠팡이츠 영어", "배달 한국"],
    },
    {
      title: "외국인 통신 개통 가이드 — SKT·KT·LGU+·알뜰폰",
      kpi: "traffic",
      category: "life",
      rationale: "ARC 다음 단계. 외국인 요금제·알뜰폰 비교 상위 랭크 기회.",
      signal: { type: "seo-gap", detail: "외국인 통신 비교 상위 10건 중 6건 오래된 정보" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["haru"],
      relatedKeywords: ["외국인 휴대폰", "알뜰폰 외국인", "SKT 외국인"],
    },
    {
      title: "한국 공휴일·계절 행사 캘린더 — 외국인 체류자용",
      kpi: "dwell_time",
      category: "life",
      rationale: "체류 기간 내 경험 극대화 주제. 브랜드 호감·체류시간 증가.",
      signal: { type: "seasonal", detail: "분기별 업데이트로 체류시간 누적" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["vibe"],
      relatedKeywords: ["한국 공휴일", "한국 축제", "Korean holidays"],
    },
    {
      title: "존댓말 기본 — 배달·카페·부동산에서 쓰는 한국어",
      kpi: "dwell_time",
      category: "life",
      rationale: "체류 초기 실용 한국어. 영상 리퍼포징 가장 쉬운 주제.",
      signal: { type: "competitor-miss", detail: "한국어 실용 가이드 경쟁 약함" },
      difficulty: "low",
      estimatedImpact: "low",
      leadAgent: "haru",
      supportAgents: ["vibe"],
      relatedKeywords: ["존댓말 기본", "한국어 일상", "Korean phrases"],
    },
  ],
  story: [
    {
      title: "Linh의 서울대 30일 — 베트남 유학생 정착 일기",
      kpi: "dwell_time",
      category: "story",
      rationale: "Top performer. 실제 유사 스토리 체류시간 평균 340초. 재방문율 높음.",
      signal: { type: "top-performer", detail: "유사 '서울 정착 일기' 체류시간 상위 10%" },
      difficulty: "medium",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["haru", "iris"],
      relatedKeywords: ["베트남 유학생", "서울 30일", "유학생 일기"],
    },
    {
      title: "Max의 성수 60일 — 독일 노마드의 워케이션 후기",
      kpi: "dwell_time",
      category: "story",
      rationale: "노마드 타겟 대표 스토리. 글로벌 커뮤니티 공유 확장 기대.",
      signal: { type: "competitor-miss", detail: "외국인 노마드 후기 경쟁 약함" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["haru", "vibe"],
      relatedKeywords: ["성수 노마드", "디지털노마드 서울", "remote work Seoul"],
    },
    {
      title: "Aki의 판교 90일 — 일본 주재원의 3개월 출장 기록",
      kpi: "dwell_time",
      category: "story",
      rationale: "주재원·법인 타겟 확보용 스토리. 일본어 리퍼포징으로 일본 마켓 확장.",
      signal: { type: "seo-gap", detail: "일본인 주재원 한국 후기 블루오션" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["haru"],
      relatedKeywords: ["판교 주재원", "일본인 서울", "駐在 韓国"],
    },
    {
      title: "호스트 인터뷰 — 공실 1년, 플라트로 월 300만원 수익 전환기",
      kpi: "dwell_time",
      category: "story",
      rationale: "호스트 유입용 스토리. B2B 마케팅과 연결되며 플라트 고유 자산.",
      signal: { type: "competitor-miss", detail: "호스트 수익 공개 각도 경쟁 0" },
      difficulty: "medium",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["haru", "echo"],
      relatedKeywords: ["호스트 인터뷰", "단기임대 수익", "공실 수익화"],
    },
    {
      title: "김지수의 성수 이사 과도기 45일 — 한국인 실거주 후기",
      kpi: "dwell_time",
      category: "story",
      rationale: "내국인 이사 과도기 세그먼트 공략. 외국인 스토리 편중 해소.",
      signal: { type: "competitor-miss", detail: "내국인 이사 후기 각도 부족" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["haru"],
      relatedKeywords: ["이사 과도기", "단기 거주", "한국인 단기임대"],
    },
    {
      title: "Yuki의 연세대 교환학생 3개월 — 신촌의 모든 것",
      kpi: "dwell_time",
      category: "story",
      rationale: "교환학생 인구 많은 중국·일본 타겟. 다국어 리퍼포징 최적.",
      signal: { type: "top-performer", detail: "유사 교환학생 스토리 재방문율 +42%" },
      difficulty: "medium",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["haru", "vibe"],
      relatedKeywords: ["연세대 교환학생", "신촌 한달", "中国 交换 首尔"],
    },
    {
      title: "제주 한달살기 — 30대 프리랜서 디자이너의 기록",
      kpi: "dwell_time",
      category: "story",
      rationale: "한달살기 시즌(4~10월) 지속 트래픽. 인스타그램 리퍼포징 효과 큼.",
      signal: { type: "seasonal", detail: "제주 한달살기 시즌 트래픽 +3.2x" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["haru", "vibe"],
      relatedKeywords: ["제주 한달살기", "프리랜서 워케이션", "제주 바다"],
    },
    {
      title: "은퇴 부부의 부산 3개월 — 시니어 한달살기 후기",
      kpi: "dwell_time",
      category: "story",
      rationale: "시니어·은퇴 세그먼트는 경쟁 최약. 사회적 영향력·브랜드 호감 큼.",
      signal: { type: "competitor-miss", detail: "시니어 한달살기 경쟁 0" },
      difficulty: "high",
      estimatedImpact: "low",
      leadAgent: "stra",
      supportAgents: ["haru"],
      relatedKeywords: ["시니어 한달살기", "은퇴 부산", "부부 워케이션"],
    },
    {
      title: "Priya의 서울 의료관광 2개월 — 인도인 환자 기록",
      kpi: "dwell_time",
      category: "story",
      rationale: "의료관광 세그먼트는 객단가 높고 미개척. 병원 제휴 브리지 기능.",
      signal: { type: "seo-gap", detail: "의료관광 체류 후기 블루오션" },
      difficulty: "high",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["haru"],
      relatedKeywords: ["의료관광", "서울 의료 체류", "medical tourism Korea"],
    },
    {
      title: "가족 3명 한달살기 — 자녀 교육과 함께한 서울 경험",
      kpi: "dwell_time",
      category: "story",
      rationale: "가족 한달살기는 방 사이즈·지역 선택 복잡. 프리미엄 매물 연결 기회.",
      signal: { type: "competitor-miss", detail: "가족 한달살기 각도 경쟁 약함" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["haru", "iris"],
      relatedKeywords: ["가족 한달살기", "자녀와 서울", "family Seoul"],
    },
  ],
  purpose: [
    {
      title: "서울 한달살기 완벽 가이드 — 2026 최신 시세·지역",
      kpi: "traffic",
      category: "purpose",
      rationale: "'서울 한달살기' 플라트 핵심 키워드. 이미 상위 랭크 유지 중 + 주기적 리프레시 필요.",
      signal: { type: "top-performer", detail: "Top Performer · 월 18.5k 조회" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["stra", "haru"],
      relatedKeywords: ["서울 한달살기", "서울 1개월 체류", "월세 한 달"],
    },
    {
      title: "출장 단기 숙소 베스트 — 강남·판교·여의도",
      kpi: "conversion",
      category: "purpose",
      rationale: "출장 시즌 꾸준한 수요. 법인 결제·세금계산서 각도가 차별점.",
      signal: { type: "search-rising", detail: "출장 단기임대 +19% QoQ" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "search",
      supportAgents: ["stra", "pulse"],
      relatedKeywords: ["출장 숙소", "법인 숙소", "business travel Seoul"],
    },
    {
      title: "이사 과도기 3주 단기임대 — 내국인 가이드",
      kpi: "conversion",
      category: "purpose",
      rationale: "내국인 타겟 확장 핵심 카테고리. 직방·다방 반대편 포지셔닝 가능.",
      signal: { type: "competitor-miss", detail: "이사 과도기 전용 경쟁 약함" },
      difficulty: "medium",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["search", "haru"],
      relatedKeywords: ["이사 과도기", "단기 거주", "이사 중 방"],
    },
    {
      title: "디지털노마드 서울 워케이션 베스트 10 동네",
      kpi: "dwell_time",
      category: "purpose",
      rationale: "노마드는 글로벌 커뮤니티 공유가 활발. 인스타·유튜브 리퍼포징 효과 큼.",
      signal: { type: "search-rising", detail: "서울 워케이션 +31% MoM" },
      difficulty: "medium",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["vibe", "haru"],
      relatedKeywords: ["서울 워케이션", "노마드 한달", "remote work Seoul"],
    },
    {
      title: "리모델링·전세보증금 대기 기간 임시 거주 가이드",
      kpi: "traffic",
      category: "purpose",
      rationale: "리모델링·전세 대기는 3~6개월 수요로 플라트 기간과 완벽 매칭.",
      signal: { type: "seo-gap", detail: "리모델링 임시 거주 각도 블루오션" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "search",
      supportAgents: ["stra"],
      relatedKeywords: ["리모델링 임시", "전세 대기", "이주 기간"],
    },
    {
      title: "교환학생 한 학기 주거 — 출국 전 체크리스트",
      kpi: "conversion",
      category: "purpose",
      rationale: "교환학생 시즌성 강함. 2월·8월 성수기 전 트래픽 확보 필수.",
      signal: { type: "seasonal", detail: "신학기 전 검색량 피크" },
      difficulty: "low",
      estimatedImpact: "high",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["교환학생 주거", "한 학기 방", "exchange housing Korea"],
    },
    {
      title: "의료관광 단기 체류 가이드 — 서울 병원 근처 숙소",
      kpi: "conversion",
      category: "purpose",
      rationale: "의료관광 객단가 높고 플라트 월 100만+ 매물과 매칭. 특수 세그먼트.",
      signal: { type: "competitor-miss", detail: "의료관광 숙소 각도 경쟁 0" },
      difficulty: "high",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["의료관광 숙소", "병원 근처 단기", "medical tourism stay"],
    },
    {
      title: "프리미엄 레지던스형 단기임대 — 주재원·임원",
      kpi: "conversion",
      category: "purpose",
      rationale: "서비스드레지던스 대비 저렴하면서 유사 서비스. 주재원 법인 직접 공략.",
      signal: { type: "seo-gap", detail: "서비스드레지던스 대안 키워드 비어있음" },
      difficulty: "high",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["pulse", "iris"],
      relatedKeywords: ["서비스드레지던스", "주재원 숙소", "executive housing"],
    },
    {
      title: "단기 파견·프로젝트 체류 — IT·컨설턴트용",
      kpi: "conversion",
      category: "purpose",
      rationale: "IT·컨설턴트 프로젝트 파견은 2~6개월 단위. 플라트 최적.",
      signal: { type: "search-rising", detail: "프로젝트 단기임대 검색 상승" },
      difficulty: "medium",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["search"],
      relatedKeywords: ["프로젝트 파견", "IT 단기임대", "컨설턴트 숙소"],
    },
    {
      title: "계절별 한달살기 — 벚꽃·단풍·눈 시즌 최적 매물",
      kpi: "traffic",
      category: "purpose",
      rationale: "시즌 콘텐츠는 재활용성 높음. 매년 업데이트로 장수 SEO.",
      signal: { type: "seasonal", detail: "계절 키워드 매년 피크" },
      difficulty: "low",
      estimatedImpact: "medium",
      leadAgent: "stra",
      supportAgents: ["vibe"],
      relatedKeywords: ["벚꽃 한달살기", "단풍 한달살기", "겨울 한달살기"],
    },
  ],
}

export function proposeIdeas(categoryId: CategoryId): ProposedIdea[] {
  return PROPOSALS[categoryId] ?? []
}

// ── Signal badge helper ───────────────────────────
export const SIGNAL_STYLES: Record<
  ProposedIdea["signal"]["type"],
  { label: string; bg: string; fg: string }
> = {
  "seo-gap": { label: "SEO 갭", bg: "#DBEAFE", fg: "#1D4ED8" },
  "top-performer": { label: "성과 패턴", bg: "#D1FAE5", fg: "#047857" },
  "seasonal": { label: "시즌", bg: "#FEF3C7", fg: "#B45309" },
  "competitor-miss": { label: "경쟁사 미스", bg: "#FCE7F3", fg: "#BE185D" },
  "search-rising": { label: "검색 급상승", bg: "#EDE9FE", fg: "#6D28D9" },
}
