import type { BlogContent } from "./schema"

/**
 * 시드: 파이프라인 테스트용 10개 샘플 콘텐츠
 * - 3가지 KPI 모두 포함
 * - 여러 상태 (idea / scheduled / drafting / reviewing / published / rewriting) 섞어서
 * - 일부는 performance 지표 포함 (발행된 것들)
 */

const NOW = "2026-04-20T10:00:00Z"

export const MOCK_CONTENTS: BlogContent[] = [
  // ── 예약 전환 (4개) ──
  {
    id: "bc-1",
    title: "서울대 근처 단기임대 추천 TOP 10 — 즉시 입주 가능",
    slug: "seoul-uni-short-term-top10",
    content_type: "region-guide",
    target_kpi: "conversion",
    status: "published",
    primary_keyword: "서울대 근처 단기임대",
    secondary_keywords: ["서울대 한달살기", "서울대 유학생 방"],
    target_audience: "유학생",
    outline: [],
    scheduled_at: "2026-03-15T09:00:00Z",
    published_at: "2026-03-15T09:00:00Z",
    metrics: {
      page_views: 4200,
      unique_visitors: 3100,
      avg_dwell_time_sec: 180,
      scroll_depth_pct: 62,
      bounce_rate_pct: 38,
      cta_clicks: 320,
      booking_conversions: 28,
      conversion_rate_pct: 0.67,
      organic_visits: 3500,
      top_queries: ["서울대 근처 방", "관악구 단기임대"],
      last_updated: "2026-04-18T00:00:00Z",
    },
    created_at: "2026-03-10T10:00:00Z",
    updated_at: "2026-03-15T09:00:00Z",
    assigned_agent_id: "content-marketer",
  },
  {
    id: "bc-2",
    title: "연세대 유학생 추천 방 8선 — 보증금 없는 옵션까지",
    slug: "yonsei-student-rooms-8",
    content_type: "region-guide",
    target_kpi: "conversion",
    status: "scheduled",
    primary_keyword: "연세대 근처 방",
    secondary_keywords: ["신촌 단기임대", "연세대 유학생"],
    target_audience: "유학생",
    outline: [],
    scheduled_at: "2026-04-25T09:00:00Z",
    created_at: "2026-04-15T10:00:00Z",
    updated_at: "2026-04-18T12:00:00Z",
    assigned_agent_id: "content-marketer",
  },
  {
    id: "bc-3",
    title: "출장 단기 숙소 베스트 — 강남·판교·여의도",
    slug: "business-trip-stay-best",
    content_type: "seo-longtail",
    target_kpi: "conversion",
    status: "drafting",
    primary_keyword: "출장 단기임대",
    secondary_keywords: ["강남 출장 숙소", "판교 1개월 숙소"],
    target_audience: "출장자",
    outline: [],
    created_at: "2026-04-18T10:00:00Z",
    updated_at: "2026-04-20T08:00:00Z",
    assigned_agent_id: "content-marketer",
  },
  {
    id: "bc-4",
    title: "건대 근처 단기임대 완벽 추천 — 유학생 인기 매물",
    slug: "konkuk-short-term-guide",
    content_type: "region-guide",
    target_kpi: "conversion",
    status: "idea",
    primary_keyword: "건대 근처 단기임대",
    secondary_keywords: ["건대입구 방", "건국대 유학생"],
    target_audience: "유학생",
    outline: [],
    created_at: "2026-04-19T14:00:00Z",
    updated_at: "2026-04-19T14:00:00Z",
  },

  // ── 오가닉 트래픽 (3개) ──
  {
    id: "bc-5",
    title: "서울 한달살기 완벽 가이드 — 2026년 최신 정보",
    slug: "seoul-monthly-stay-guide-2026",
    content_type: "seo-longtail",
    target_kpi: "traffic",
    status: "published",
    primary_keyword: "서울 한달살기",
    secondary_keywords: ["서울 단기임대", "서울 1개월 숙소"],
    target_audience: "디지털노마드",
    outline: [],
    scheduled_at: "2026-02-20T09:00:00Z",
    published_at: "2026-02-20T09:00:00Z",
    metrics: {
      page_views: 18500,
      unique_visitors: 14200,
      avg_dwell_time_sec: 210,
      scroll_depth_pct: 58,
      bounce_rate_pct: 42,
      cta_clicks: 420,
      booking_conversions: 31,
      conversion_rate_pct: 0.22,
      organic_visits: 16800,
      top_queries: ["서울 한달살기", "서울 한달 살기 후기", "서울 단기임대 가격"],
      last_updated: "2026-04-18T00:00:00Z",
    },
    created_at: "2026-02-10T10:00:00Z",
    updated_at: "2026-02-20T09:00:00Z",
    assigned_agent_id: "seo-expert",
  },
  {
    id: "bc-6",
    title: "외국인을 위한 한국 단기임대 가이드 — 계약부터 ARC까지",
    slug: "foreigner-korea-rental-guide",
    content_type: "seo-longtail",
    target_kpi: "traffic",
    status: "reviewing",
    primary_keyword: "한국 단기임대 외국인",
    secondary_keywords: ["ARC 발급", "korea short term rental"],
    target_audience: "외국인 유학생",
    outline: [],
    scheduled_at: "2026-04-28T09:00:00Z",
    created_at: "2026-04-12T10:00:00Z",
    updated_at: "2026-04-19T16:00:00Z",
    assigned_agent_id: "seo-expert",
  },
  {
    id: "bc-7",
    title: "에어비앤비 vs 단기임대, 월 단위는 어디가 나을까?",
    slug: "airbnb-vs-short-term-comparison",
    content_type: "seo-longtail",
    target_kpi: "traffic",
    status: "published",
    primary_keyword: "에어비앤비 vs 단기임대",
    secondary_keywords: ["한달살기 플랫폼 비교"],
    target_audience: "일반",
    outline: [],
    scheduled_at: "2026-03-01T09:00:00Z",
    published_at: "2026-03-01T09:00:00Z",
    metrics: {
      page_views: 420,
      unique_visitors: 380,
      avg_dwell_time_sec: 95,
      scroll_depth_pct: 35,
      bounce_rate_pct: 72,
      cta_clicks: 8,
      booking_conversions: 1,
      conversion_rate_pct: 0.26,
      organic_visits: 310,
      top_queries: ["에어비앤비 단기임대 비교"],
      last_updated: "2026-04-18T00:00:00Z",
    },
    created_at: "2026-02-25T10:00:00Z",
    updated_at: "2026-03-01T09:00:00Z",
    assigned_agent_id: "seo-expert",
  },

  // ── 체류시간 / 브랜드 (3개) ──
  {
    id: "bc-8",
    title: "베트남 유학생의 서울 정착 일기 — 첫 30일",
    slug: "vietnamese-student-seoul-diary",
    content_type: "guest-story",
    target_kpi: "dwell_time",
    status: "published",
    primary_keyword: "유학생 한국 자취 후기",
    secondary_keywords: ["서울 한달 첫 경험"],
    target_audience: "예비 유학생",
    outline: [],
    scheduled_at: "2026-03-22T09:00:00Z",
    published_at: "2026-03-22T09:00:00Z",
    metrics: {
      page_views: 3200,
      unique_visitors: 2800,
      avg_dwell_time_sec: 340,
      scroll_depth_pct: 78,
      bounce_rate_pct: 28,
      cta_clicks: 110,
      booking_conversions: 6,
      conversion_rate_pct: 0.19,
      organic_visits: 1800,
      top_queries: ["베트남 유학생 후기", "서울 한달살기 일기"],
      last_updated: "2026-04-18T00:00:00Z",
    },
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-22T09:00:00Z",
    assigned_agent_id: "content-marketer",
  },
  {
    id: "bc-9",
    title: "20평 원룸으로 월 300만원 수익, 호스트 인터뷰",
    slug: "host-interview-300k-monthly",
    content_type: "host-story",
    target_kpi: "dwell_time",
    status: "drafting",
    primary_keyword: "단기임대 호스트 수익",
    secondary_keywords: ["원룸 호스트 인터뷰"],
    target_audience: "예비 호스트",
    outline: [],
    created_at: "2026-04-14T10:00:00Z",
    updated_at: "2026-04-19T18:00:00Z",
    assigned_agent_id: "content-marketer",
  },
  {
    id: "bc-10",
    title: "디지털노마드로 서울에서 한 달 — 일과 휴식의 균형",
    slug: "digital-nomad-seoul-balance",
    content_type: "lifestyle",
    target_kpi: "dwell_time",
    status: "rewriting",
    primary_keyword: "디지털노마드 서울 한달",
    secondary_keywords: ["서울 워케이션"],
    target_audience: "디지털노마드",
    outline: [],
    scheduled_at: "2026-02-10T09:00:00Z",
    published_at: "2026-02-10T09:00:00Z",
    metrics: {
      page_views: 280,
      unique_visitors: 250,
      avg_dwell_time_sec: 110,
      scroll_depth_pct: 40,
      bounce_rate_pct: 65,
      cta_clicks: 4,
      booking_conversions: 0,
      conversion_rate_pct: 0,
      organic_visits: 180,
      top_queries: ["서울 디지털노마드"],
      last_updated: "2026-04-18T00:00:00Z",
    },
    created_at: "2026-02-05T10:00:00Z",
    updated_at: "2026-04-19T10:00:00Z",
    assigned_agent_id: "content-marketer",
  },
]
